-- Populate beat_template table with 40-beat structure
INSERT INTO public.beat_template (id, title, type, function) VALUES
(1, 'Opening Image', 'Setup', 'Visual metaphor that sets tone and theme'),
(2, 'Theme Stated', 'Setup', 'Central theme/lesson hinted at early'),
(3, 'Set-Up', 'Setup', 'Introduce protagonist in their ordinary world'),
(4, 'Catalyst', 'Setup', 'Inciting incident that disrupts normal life'),
(5, 'Debate', 'Setup', 'Protagonist hesitates about the journey ahead'),
(6, 'Break into Two', 'Setup', 'Protagonist commits to the adventure/change'),
(7, 'B Story', 'Fun and Games', 'Subplot introduced, often romantic or friendship'),
(8, 'Fun and Games', 'Fun and Games', 'Promise of the premise delivered'),
(9, 'Midpoint', 'Fun and Games', 'False victory or defeat; stakes raised'),
(10, 'Bad Guys Close In', 'Bad Guys Close In', 'Opposition strengthens; problems multiply'),
(11, 'All Is Lost', 'Bad Guys Close In', 'Lowest point; hero loses everything'),
(12, 'Dark Night of the Soul', 'Bad Guys Close In', 'Hero reflects on failure and loss'),
(13, 'Break into Three', 'Finale', 'Hero discovers solution; final plan formed'),
(14, 'Finale', 'Finale', 'Climactic battle; all conflicts resolved'),
(15, 'Final Image', 'Finale', 'Opposite of opening image; transformation complete'),
(16, 'Character Introduction', 'Setup', 'Detailed introduction of main characters'),
(17, 'World Building', 'Setup', 'Establish rules and reality of story world'),
(18, 'Stakes Established', 'Setup', 'What protagonist stands to gain or lose'),
(19, 'First Obstacle', 'Fun and Games', 'Initial challenge in new world'),
(20, 'Mentor Appears', 'Fun and Games', 'Wise guide provides tools or knowledge'),
(21, 'First Victory', 'Fun and Games', 'Early success builds confidence'),
(22, 'Deeper Conflict', 'Fun and Games', 'Underlying tensions surface'),
(23, 'Point of No Return', 'Fun and Games', 'Hero cannot return to old life'),
(24, 'Revelation', 'Bad Guys Close In', 'Important truth revealed'),
(25, 'Betrayal', 'Bad Guys Close In', 'Ally turns enemy or trust broken'),
(26, 'Hope Spot', 'Bad Guys Close In', 'Brief moment of potential victory'),
(27, 'Sacrifice', 'Bad Guys Close In', 'Hero or ally makes difficult choice'),
(28, 'Wisdom Gained', 'Bad Guys Close In', 'Hero learns crucial lesson'),
(29, 'New Plan', 'Finale', 'Strategy formed with new understanding'),
(30, 'Gathering Allies', 'Finale', 'Hero reunites with or gains supporters'),
(31, 'Final Approach', 'Finale', 'Movement toward final confrontation'),
(32, 'Ordeal', 'Finale', 'Greatest fear faced'),
(33, 'Resurrection', 'Finale', 'Hero emerges transformed'),
(34, 'Return with Elixir', 'Finale', 'Hero brings wisdom/gift to ordinary world'),
(35, 'Supporting Cast', 'Setup', 'Introduction of key supporting characters'),
(36, 'Backstory Revealed', 'Fun and Games', 'Important history unveiled'),
(37, 'False Lead', 'Bad Guys Close In', 'Misleading clue or wrong direction'),
(38, 'Moral Choice', 'Bad Guys Close In', 'Ethical dilemma tests character'),
(39, 'Final Test', 'Finale', 'Ultimate challenge of growth'),
(40, 'New Beginning', 'Finale', 'World changed; new status quo established');